ALTER TABLE player ADD COLUMN guild_id INTEGER REFERENCES guild(id) ON DELETE SET NULL;
ALTER TABLE player ADD COLUMN campaign_id INTEGER REFERENCES campaign(id) ON DELETE SET NULL;
ALTER TABLE player_character ADD COLUMN player_id INTEGER REFERENCES player(id) ON DELETE SET NULL;
ALTER TABLE campaign ADD COLUMN game_master INTEGER REFERENCES player(id) ON DELETE SET NULL;
ALTER TABLE campaign_session ADD COLUMN campaign_id INTEGER REFERENCES campaign(id) ON DELETE SET NULL;
ALTER TABLE note ADD COLUMN session_id INTEGER REFERENCES campaign_session(id) ON DELETE SET NULL;